import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, ShoppingCart, User, Star, Truck, ShieldCheck, CreditCard, MessageCircle, Plus, Pencil, Trash2, Package, ClipboardList, Save, Home } from 'lucide-react';
import './style.css';

const ADMIN_PASSWORD = '123456';
const categories = ['Todos','Pianos Digitais','Teclados','Controladores','Pedais','Suportes','Áudio','Acessórios','Promoções'];
const defaultProducts = [
{id:'piano-harmonia-px88',name:'Piano Digital Harmonia PX-88',sku:'TP-PX88',category:'Pianos Digitais',competitorPrice:4999,price:3499,stock:8,image:'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?q=80&w=1200&auto=format&fit=crop',description:'Piano digital com 88 teclas, timbres realistas, design moderno e excelente resposta para estudo, igreja, palco e home studio.',tag:'30% OFF',rating:'4.9'},
{id:'teclado-maestro-61',name:'Teclado Arranjador Maestro 61',sku:'TP-MA61',category:'Teclados',competitorPrice:2199,price:1539,stock:12,image:'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1200&auto=format&fit=crop',description:'Teclado arranjador com 61 teclas, ritmos, timbres, acompanhamento automático e recursos ideais para iniciantes e músicos práticos.',tag:'Oferta',rating:'4.8'},
{id:'pedal-sustain-prostage',name:'Pedal Sustain ProStage',sku:'TP-PS01',category:'Pedais',competitorPrice:249,price:174,stock:30,image:'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?q=80&w=1200&auto=format&fit=crop',description:'Pedal sustain resistente, compatível com diversos teclados e pianos digitais. Ideal para estudo, gravação e apresentações.',tag:'Mais vendido',rating:'4.7'},
{id:'suporte-x-duplo',name:'Suporte X Duplo Reforçado',sku:'TP-SX02',category:'Suportes',competitorPrice:399,price:279,stock:20,image:'https://images.unsplash.com/photo-1507838153414-b4b713384a76?q=80&w=1200&auto=format&fit=crop',description:'Suporte em X duplo reforçado para teclados e pianos digitais, com regulagem de altura e estrutura estável.',tag:'30% OFF',rating:'4.9'}
];
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function price30(v){return Math.round(Number(v||0)*0.7);}
function slug(t){return String(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function load(k,f){try{const s=localStorage.getItem(k);return s?JSON.parse(s):f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v));}
function App(){
 const [page,setPage]=useState(location.pathname==='/admin'?'admin':'home');
 const [products,setProducts]=useState(load('teclaprime_products',defaultProducts));
 const [orders,setOrders]=useState(load('teclaprime_orders',[]));
 const [search,setSearch]=useState(''); const [category,setCategory]=useState('Todos');
 useEffect(()=>save('teclaprime_products',products),[products]); useEffect(()=>save('teclaprime_orders',orders),[orders]);
 const filtered=useMemo(()=>products.filter(p=>(category==='Todos'||p.category===category)&&(p.name.toLowerCase().includes(search.toLowerCase())||p.sku.toLowerCase().includes(search.toLowerCase()))),[products,search,category]);
 function makeOrder(p){const customer=prompt('Nome do cliente:');if(!customer)return;const phone=prompt('WhatsApp do cliente:')||'';setOrders([{id:'PED-'+Date.now(),date:new Date().toLocaleString('pt-BR'),customer,phone,product:p.name,price:p.price,status:'Novo'},...orders]);alert('Pedido criado no painel!');}
 if(page==='admin')return <Admin products={products} setProducts={setProducts} orders={orders} setOrders={setOrders} goHome={()=>{history.pushState(null,'','/');setPage('home')}}/>;
 return <div className="site"><header className="header"><div className="topbar"><div className="brand"><div className="brandIcon">TP</div><div><h1>TeclaPrime</h1><p>Instrumentos & Áudio</p></div></div><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto..."/><button><Search size={20}/></button></div><div className="actions"><button onClick={()=>{history.pushState(null,'','/admin');setPage('admin')}}><User size={18}/> Admin</button><button className="cart"><ShoppingCart size={18}/> Carrinho</button></div></div><nav className="nav">{categories.map(c=><a className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</a>)}</nav></header><section className="hero"><div className="heroInner"><div><span className="pill">Loja de instrumentos</span><h2>Pianos digitais com até 30% OFF</h2><p>Teclados, pianos digitais, acessórios e áudio com atendimento rápido e preço competitivo.</p><button className="primary">Ver ofertas</button></div><img src="https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?q=80&w=1200&auto=format&fit=crop"/></div></section><section className="benefits">{[['Envio rápido',Truck],['Compra segura',ShieldCheck],['Até 12x',CreditCard],['WhatsApp',MessageCircle]].map(([t,Icon])=><div className="benefit" key={t}><Icon/><b>{t}</b></div>)}</section><main className="section"><div className="sectionHead"><div><p>Produtos</p><h3>Catálogo TeclaPrime</h3></div><button onClick={()=>{history.pushState(null,'','/admin');setPage('admin')}}>Cadastrar produto</button></div><div className="products">{filtered.map(p=><article className="product" key={p.id}><div className="productImg"><img src={p.image}/><span>{p.tag||'30% OFF'}</span></div><div className="productInfo"><div className="rating"><Star size={15} fill="currentColor"/> {p.rating||'4.8'} | SKU: {p.sku}</div><h4>{p.name}</h4><p className="desc">{p.description}</p><p className="old">{money(p.competitorPrice)}</p><p className="price">{money(p.price)}</p><p className="installments">Estoque: {p.stock} | até 12x</p><button onClick={()=>makeOrder(p)}>Comprar</button></div></article>)}</div></main><a className="whatsapp" href="https://wa.me/5500000000000?text=Olá,%20quero%20comprar%20na%20TeclaPrime" target="_blank">WhatsApp</a><footer><h4>TeclaPrime</h4><p>Instrumentos musicais, teclados, pianos digitais e acessórios.</p></footer></div>;
}
function Admin({products,setProducts,orders,setOrders,goHome}){
 const [logged,setLogged]=useState(localStorage.getItem('teclaprime_admin')==='yes'); const [password,setPassword]=useState('');
 const empty={id:'',name:'',sku:'',category:'Pianos Digitais',competitorPrice:'',price:'',stock:'',image:'',description:'',tag:'30% OFF',rating:'4.8'}; const [form,setForm]=useState(empty);
 function login(){if(password===ADMIN_PASSWORD){localStorage.setItem('teclaprime_admin','yes');setLogged(true)}else alert('Senha errada. Senha inicial: 123456')}
 function edit(p){setForm(p);scrollTo(0,0)} function remove(id){if(confirm('Apagar esse produto?'))setProducts(products.filter(p=>p.id!==id))}
 function submit(e){e.preventDefault();const item={...form,id:form.id||slug(form.name)||'produto-'+Date.now(),competitorPrice:Number(form.competitorPrice||0),price:Number(form.price||price30(form.competitorPrice)),stock:Number(form.stock||0)};const exists=products.some(p=>p.id===item.id);setProducts(exists?products.map(p=>p.id===item.id?item:p):[item,...products]);setForm(empty);alert('Produto salvo!')}
 if(!logged)return <div className="adminLogin"><div className="loginBox"><h1>Painel TeclaPrime</h1><p>Digite a senha para entrar.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha"/><button onClick={login}>Entrar</button><small>Senha inicial: 123456</small></div></div>;
 return <div className="admin"><aside><h2>TeclaPrime</h2><button onClick={goHome}><Home size={18}/> Ver loja</button><button><Package size={18}/> Produtos</button><button><ClipboardList size={18}/> Pedidos</button></aside><main><div className="adminTop"><h1>Painel de Produtos</h1><button onClick={()=>{localStorage.removeItem('teclaprime_admin');location.reload()}}>Sair</button></div><form className="form" onSubmit={submit}><h3><Plus size={20}/> Cadastrar / Editar produto</h3><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do produto" required/><input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} placeholder="SKU"/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.filter(c=>c!=='Todos').map(c=><option key={c}>{c}</option>)}</select><input type="number" value={form.competitorPrice} onChange={e=>setForm({...form,competitorPrice:e.target.value})} placeholder="Preço concorrente"/><div className="row"><input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Seu preço"/><button type="button" onClick={()=>setForm({...form,price:price30(form.competitorPrice)})}>Aplicar -30%</button></div><input type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} placeholder="Estoque"/><input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="URL da foto"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descrição do produto"/><button className="save"><Save size={18}/> Salvar produto</button></form><section className="adminCards"><div><b>{products.length}</b><span>Produtos</span></div><div><b>{orders.length}</b><span>Pedidos</span></div><div><b>{money(products.reduce((a,p)=>a+Number(p.price||0)*Number(p.stock||0),0))}</b><span>Valor em estoque</span></div></section><h2>Produtos cadastrados</h2><div className="table">{products.map(p=><div className="tableRow" key={p.id}><img src={p.image}/><div><b>{p.name}</b><small>{p.sku} | {p.category} | Estoque: {p.stock}</small></div><div><span className="line">{money(p.competitorPrice)}</span><b>{money(p.price)}</b></div><button onClick={()=>edit(p)}><Pencil size={16}/></button><button onClick={()=>remove(p.id)}><Trash2 size={16}/></button></div>)}</div><h2>Pedidos</h2><div className="table">{orders.length===0&&<p className="empty">Nenhum pedido ainda.</p>}{orders.map(o=><div className="tableRow order" key={o.id}><div><b>{o.id}</b><small>{o.date}</small></div><div><b>{o.customer}</b><small>{o.phone}</small></div><div><b>{o.product}</b><small>{money(o.price)}</small></div><button onClick={()=>setOrders(orders.filter(x=>x.id!==o.id))}>Excluir</button></div>)}</div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
